### ISSUE TITLE
Output to single css file

### ISSUE THREAD

**Issue by Karl456** [MohamedLamineAllal/laravel-mix-glob#26]
Is it possible to output the compiled sass to a single css file?

At the moment I have the following:

```
mixGlob.sass([
    'Modules/Admins/sass/app.scss',
    'Modules/!(Admins)/sass/**/*.scss'
], 'public/css/app.css')
```

However, this will output each sass file it finds as a single css file. I want it to compile the sass and output to a single css file.

**Comment by MohamedLamineAllal** [comment]
HI sir! Sorry for not being fast to respond! I'm into a lot of work!

Actually that's not supported as it is!

The way how laravel-mix-glob work is that it apply the glob matching! Then for each file it apply the native mix method! And it save us the headache of doing that manually for each file!

We can add the functionality that you asked for! I can do it myself! I can motivate you to implement it yourself!

Actually i like to have some contributors that help grow and manage the project! 

In short what one can do! is to add one option! Or create completly a new method! Which do the bundling!
Basically then the process should go as follow!

- We use this same method and then write a file from all the file to a new one! and delete them on the go! But that add those extra write and so is more like a hack then a good solution!
- Or we can directly use webpack! We see how laravel mix is implementing it! And we make a bundling! Webpack support such things! We can directly look at webpack! And we can have the feature directly implemented in laravel-mix-glob! And the web pack road can is more of a clean and good way!

I prefere webpack way!

If you like to give it a try! I can help you! Otherwise i'll look at adding this feature!

I haven't checked where laravel-mix is right now! it's nice to check what are all the new features!

**Comment by MohamedLamineAllal** [comment]
I'll close the issue! Feel free to reopen!
